name: Main

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: make setup

    - name: Build & Package
      run: make

    - name: Test
      run: make test

    - name: Push packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        dotnet nuget push artifacts/**/*.nupkg --api-key ${{ secrets.FEEDZ_IO_TOKEN }} --source https://f.feedz.io/nvd/libmodbus/nuget/index.json --skip-duplicate
